[package]
edition = "2018"
name = "ra_prof"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[lib]
doctest = false

[dependencies]
ra_arena = { path = "../ra_arena" }
once_cell = "1.3.1"
backtrace = { version = "0.3.44", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.3.2", optional = true }
jemalloc-ctl = { version = "0.3.3", optional = true }

[features]
jemalloc = [ "jemallocator", "jemalloc-ctl" ]
cpu_profiler = []
