status = [
    "Rust (ubuntu-latest)",
    "Rust (windows-latest)",
    "Rust (macos-latest)",
    "TypeScript (ubuntu-latest)",
    "TypeScript (windows-latest)",
    "TypeScript (macos-latest)",
]
delete_merged_branches = true
